# Generated by Django 4.2 on 2023-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_types_ap'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_ap',
            name='Types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
