# Generated by Django 4.2 on 2023-05-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_types_ap_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_ap',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
