# Generated by Django 4.2 on 2023-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('UEmail', models.EmailField(blank=True, max_length=60, null=True)),
                ('UPassword', models.CharField(blank=True, max_length=60, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('UsImage', models.ImageField(blank=True, null=True, upload_to='userimage')),
            ],
        ),
    ]
