# Generated by Django 3.2.10 on 2023-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingName', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneB', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Members', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
